export interface StoreBusinessDistrict {
  id?: string | undefined
  brandId?: string | undefined
  businessDistrictCode?: string | undefined
  businessDistrictName?: string | undefined
  businessDistrictDesc?: string | undefined
  businessDistrictAddress?: string | undefined
  countryCode?: string | undefined
  provinceCode?: string | undefined
  cityCode?: string | undefined
  areaCode?: string | undefined
  countryName?: string | undefined
  provinceName?: string | undefined
  cityName?: string | undefined
  areaName?: string | undefined
  businessDistrictRadius?: string | undefined | any
  businessDistrictLevelId?: string | undefined
  businessDistrictTypeId?: string | undefined
  centerLat?: string | undefined
  centerLng?: string | undefined
  isDelete?: string | undefined
  createTime?: string | undefined
  createBy?: string | undefined
  updateTime?: string | undefined
  updateBy?: string | undefined
  traceId?: string | undefined
  versionNum?: string | undefined
  tenantId?: string | undefined
  createUserName?: string | undefined
  updateUserName?: string | undefined
}
