<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>peanut-gateway</artifactId>
  <build>
    <finalName>app</finalName>
    <plugins>
      <plugin>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <includeSystemScope>true</includeSystemScope>
          <mainClass>com.olivia.PortalBootstrapApplication</mainClass>

        </configuration>
        <groupId>org.springframework.boot</groupId>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <artifactId>peanut-sdk</artifactId>
      <groupId>com.olivia</groupId>
    </dependency>


    <dependency>
      <artifactId>peanut-base</artifactId>
      <groupId>com.olivia</groupId>
    </dependency>

  </dependencies>

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <properties>


  </properties>
</project>