<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.olivia</groupId>
    <artifactId>peanut-portal-all</artifactId>
    <version>3.0.0-20251013-SNAPSHOT</version>
  </parent>

  <artifactId>peanut-gateway</artifactId>

  <dependencies>
    <dependency>
      <groupId>com.olivia</groupId>
      <artifactId>peanut-aps</artifactId>
    </dependency>
<!--    <dependency>-->
<!--      <groupId>com.olivia</groupId>-->
<!--      <artifactId>peanut-base</artifactId>-->
<!--    </dependency>-->
  </dependencies>
  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <build>
    <finalName>app</finalName>
    <plugins>
      <plugin>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <includeSystemScope>true</includeSystemScope>
          <mainClass>com.olivia.PortalBootstrapApplication</mainClass>

        </configuration>
        <groupId>org.springframework.boot</groupId>
      </plugin>
    </plugins>
  </build>
</project>